# Generated by Django 3.0.7 on 2020-06-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img',
        ),
    ]
